{% set version = "3.44.0.3" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-h2o
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/h2o_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/h2o/h2o_{{ version }}.tar.gz
  sha256: 61a85f6c2f15e8e96839f8a4fd3a45eaa6bca90517bb20a4dd36e951d6fd0c82

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcurl
    - r-jsonlite
    - openjdk
  run:
    - r-base
    - r-rcurl
    - r-jsonlite
    - openjdk

test:
  commands:
    - $R -e "library('h2o')"           # [not win]
    - "\"%R%\" -e \"library('h2o')\""  # [win]

about:
  home: https://github.com/h2oai/h2o-3
  license: Apache-2.0
  summary: R interface for 'H2O', the scalable open source machine learning platform that offers parallelized implementations of many supervised and unsupervised machine learning algorithms such as Generalized Linear Models (GLM), Gradient Boosting Machines (including XGBoost), Random Forests, Deep Neural Networks (Deep
    Learning), Stacked Ensembles, Naive Bayes, Generalized Additive Models (GAM), Cox Proportional Hazards, K-Means, PCA, Word2Vec, as well as a fully automatic machine learning algorithm (H2O AutoML).
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
